# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'login.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.
from PyQt5.QtWidgets import QWidget, QApplication, QTextEdit
import sys
from PyQt5 import QtCore, QtGui, QtWidgets
import pymysql
import asyncio
class Ui_Form(QWidget):
    def __init__(self, parent=None):
        super(Ui_Form, self).__init__(parent)
        self.resize(795, 446)
        self.pushButton = QtWidgets.QPushButton(self)
        self.pushButton.setGeometry(QtCore.QRect(540, 210, 101, 81))
        self.pushButton.setObjectName("pushButton")
        self.textBrowser = QtWidgets.QTextBrowser(self)
        self.textBrowser.setGeometry(QtCore.QRect(10, 10, 191, 51))
        self.textBrowser.setObjectName("textBrowser")
        self.lineEdit = QtWidgets.QLineEdit(self)
        self.lineEdit.setGeometry(QtCore.QRect(280, 160, 171, 31))
        self.lineEdit.setObjectName("lineEdit")
        self.lineEdit_2 = QtWidgets.QLineEdit(self)
        self.lineEdit_2.setGeometry(QtCore.QRect(280, 230, 171, 31))
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.label = QtWidgets.QLabel(self)
        self.label.setGeometry(QtCore.QRect(240, 160, 101, 41))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self)
        self.label_2.setGeometry(QtCore.QRect(240, 240, 72, 15))
        self.label_2.setObjectName("label_2")

        self.retranslateUi(self)
        QtCore.QMetaObject.connectSlotsByName(self)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "登录"))
        self.pushButton.setText(_translate("Form", "登录"))
        self.lineEdit.setPlaceholderText(_translate("Form", "请输入账号"))
        self.lineEdit_2.setPlaceholderText(_translate("Form", "请输入密码"))
        self.label.setText(_translate("Form", "账号："))
        self.label_2.setText(_translate("Form", "密码："))
        self.pushButton.clicked.connect(self.login)
    def login(self):
        if(len(self.lineEdit.text())==0):
            self.textBrowser.setText("请输入账号")
            self.textBrowser.repaint()
        else:
            if (len(self.lineEdit_2.text()) == 0):
                self.textBrowser.setText("请输入密码")
                self.textBrowser.repaint()
            else:
                con=pymysql.connect(
                    host='1.15.95.29',
                    user='root',
                    password='live2018',
                    charset='utf8',
                    database='login'
                )
                sql="select password from login where name ='%s'"%self.lineEdit.text()
                cursor=con.cursor()
                cursor.execute(sql)
                res=cursor.fetchone()
                result=''.join(res)
                if (result==self.lineEdit_2.text()):
                    self.textBrowser.setText("登录成功")
                    self.textBrowser.repaint()
                    asyncio.wait(2)
                    self.close()
                    self.success()
                else:
                    self.textBrowser.setText("密码或账号错误，请重新输入")
                    self.textBrowser.repaint()
                    asyncio.wait(10)
                    self.login()
                    self.close()
    def success(self):
        import main
        self.one=main.Ui_Form()
        self.one.show()
if __name__ == '__main__':
    app = QApplication(sys.argv)
    main = Ui_Form()
    main.show()
    sys.exit(app.exec_())
